# Generated by Django 3.2 on 2022-03-12 18:23

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.CharField(default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='localisation',
            field=places.fields.PlacesField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
