# Generated by Django 3.2 on 2022-03-12 18:46

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220312_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='localisation',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
