# Generated by Django 3.2 on 2022-03-12 19:35

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_hotel_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='localisation',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
