# Generated by Django 3.2 on 2022-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220314_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='type',
            field=models.CharField(choices=[('passage', 'passage'), ('nuitee', 'nuitee'), ('sejour', 'sejour')], default='passage', max_length=30, verbose_name='type de forfait'),
        ),
    ]
