# Generated by Django 3.2 on 2022-03-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_forfait_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forfait',
            old_name='Hotel',
            new_name='hotel',
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField()),
                ('climatisation', models.BooleanField()),
                ('piscine', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hotel')),
            ],
        ),
    ]
