# Generated by Django 3.2 on 2022-03-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220314_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagehotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='base.hotel'),
        ),
    ]
