# Generated by Django 3.2.8 on 2022-03-15 00:16

from django.db import migrations, models
import django.db.models.deletion
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220314_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forfait',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forfaits', to='base.hotel'),
        ),
    ]
